name: Deploy Golf Regel App

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

# Legg til environment for GitHub Pages
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug - Check files and secrets
      run: |
        echo "=== FILES IN ROOT ==="
        ls -la
        echo ""
        echo "=== TEMPLATE FILE EXISTS? ==="
        test -f index-template.html && echo "✅ Template file found" || echo "❌ Template file missing"
        echo ""
        echo "=== CHECKING FOR PLACEHOLDERS ==="
        grep -n "YOUR_.*_API_KEY" index-template.html || echo "No placeholders found in template"
        echo ""
        echo "=== SECRETS STATUS ==="
        echo "Anthropic key length: ${#ANTHROPIC_API_KEY}"
        echo "Serper key length: ${#SERPER_API_KEY}" 
        echo "Tavily key length: ${#TAVILY_API_KEY}"
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    - name: Create index.html with API keys
      run: |
        cp index-template.html index.html
        sed -i "s/YOUR_ANTHROPIC_API_KEY/${{ secrets.ANTHROPIC_API_KEY }}/g" index.html
        sed -i "s/YOUR_SERPER_API_KEY/${{ secrets.SERPER_API_KEY }}/g" index.html  
        sed -i "s/YOUR_TAVILY_API_KEY/${{ secrets.TAVILY_API_KEY }}/g" index.html
        echo "✅ Replacement completed"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
